common:
  - docker_plugin: &docker
      docker#v3.0.0:
        image: alpine

steps:
  - command: uname -a
    plugins:
      - *docker 
  - command: uname -a
    plugins:
      - <<: *docker
          docker#v5.0.0:
            image: ubuntu
