steps:
  - command: pytest
    label: ":snake: :test_tube:"

  - command: cd app && gotestsum --junitfile junit.xml ./...
    label: ":go: :test_tube:"
    plugins:
      - test-collector#v1.10.0:
          files: "./go/junit-*.xml"
          format: "junit"
      
