steps:
  - label: ":snyk: So Snyky!"
    plugins:
    - /Users/jeremy/dev/plugins/snyk-buildkite-plugin#snyk-mvp:
        scan: 'container'
        token-env: 'BUILDKITE_SNYK_TOKEN'
        image: 'alpine'
      

