steps:
  - command: echo "Hello World"
    key: "hello"

  - key: "blocker"
    block: "Run Visual Regression Test?"
    fields:
      - select: "Run regression test?"
        key: "regression"
        options:
          - label: "yes"
            value: "yes"
          - label: "no"
            value: "no"
    depends_on: "hello"

  - command: |
      if [$(buildkite-agent meta-data get "regression") == "yes"];
        echo "Upload regression test steps"
      fi
    depends_on: "blocker"
