steps:
  - command: echo "Hello World"
    key: "hello"

  - key: "blocker"
    block: "Run Visual Regression Test?"
    prompt: "Do you want to run the visual regression test?"
    options:
      - "yes"
      - "no"
    value: "regression"
    depends_on: "hello"

  - command: |
    if [$(buildkite-agent meta-data get "regression") == "yes"];
      buildkite-agent pipeline upload regression-test.yml
    fi
    depends_on: "blocker"
