
steps:
  - label: "WAIT_STEP: $WAIT_STEP"
    command: sleep 30
    if: build.env("WAIT_STEP") == "a"
    key: a
    
  - label: "WAIT_STEP: $WAIT_STEP"
    command: sleep 10
    if: build.env("WAIT_STEP") == "b"
    key: b
 
  - wait: ~
    if: build.env("WAIT_STEP") == "a"
    depends_on: a

  - wait: ~
    if: build.env("WAIT_STEP") == "b"
    depends_on: b
    
  - command: echo done waiting for step $WAIT_STEP
