steps:
  - command: echo "Hello World"
    key: "hello"

  - key: "blocker"
    block: "Run Visual Regression Test?"
    fields:
      - key: "regression"
      - hint: "Do you want to run the visual regression test?"
      - options:
        label: "yes"
        value: "yes"
        label: "no"
        value: "no"
    depends_on: "hello"

  - command: |
      if [$(buildkite-agent meta-data get "regression") == "yes"];
        echo "Upload regression test steps"
      fi
    depends_on: "blocker"
