steps:
  - command: echo "Hello World"
    key: "hello"

  - key: "blocker"
    block: "Run Visual Regression Test?"
    fields:
      - select: "Run regression test?"
        key: "regression"
        options:
          - label: "yes"
            value: "yes"
          - label: "no"
            value: "no"
    depends_on: "hello"

  - label: "Upload Regression Test Steps"
    command: |
      if [ "$(buildkite-agent meta-data get "regression")" == "yes" ];
      then
        buildkite-agent pipeline upload regression.yml
      fi
    depends_on: "blocker"
